### PR TITLE
document the changes for 3.10.2.1, and bump up the version #

### PR DESCRIPTION
**Pull request by mlite**
prepare for 3.10.2.1 release

### CODE REVIEW

**Comment by hvr** [comment]
wait second... why the version bump?!

**Comment by hvr** [comment]
nevermind... for a second I thought 3.10.1 was the latest released version

**Comment by hvr** [comment]
something is off here... there is no 3.10.2 Git release tag... :-(

**Comment by mlite** [comment]
3.10.2 was omitted in the previous release.

**Comment by mlite** [comment]
tag need  to be annotated. revoke the request and create another one.

**Pull request closed without merging**
