### PR TITLE
Remove prototypes/ and private/

### PR DESCRIPTION
**Pull request by michalt**
As already discussed in #6 the directories don't really contain anything useful at this point (and might actually be confusing for newcomers).

### CODE REVIEW

**Comment by jstolarek** [comment]
I'll review that and merge it sometime next week.

**Comment by michalt** [comment]
Cool, thanks!

**Comment by jstolarek** [comment]
Looks like I won't have time to review this next week, so either it has to wait or someone else with push permissions needs to take a look. (In case of the latter, please don't use GitHub's "Merge pull request" but do a local ff-merge and push.)

**Comment by mlite** [comment]
merged to master

**Pull request merged**
