### PR TITLE
Cleaned useless comments and removed unused modules (ticket #6)

### PR DESCRIPTION
**Pull request by lexpank**

### CODE REVIEW

**Comment by jstolarek** [comment]
@michalt, are you able to verify whether these changes break building of the paper? With or without them the paper does not build on my machine.

Anyway, I vote to remove the paper as well. This repo should really contain only code. We can make a tag for the revision that still contains the paper, so it is easy to check it out if necessary.

**Comment by michalt** [comment]
@jstolarek No I haven't checked. But thinking about it, I'm also convinced that we should simply remove the whole `paper/` directory. It makes some of the code less readable and sooner or later the code will diverge with what is in the paper anyway.
So I'd be happy with updating this PR to also remove the paper (or alternatively merging it and quickly sending another one to do that).

**Comment by jstolarek** [comment]
@AlexanderPankiv can you update this PR to also remove the paper/ directory?

**Comment by lexpank** [comment]
@jstolarek no problem. I don't see any reason why would it be in repo. Maybe I should also create branch with it itself?

**Comment by mlite** [comment]
I cannot image how people can use the library without first reading the 
paper.   The behavior of this library is just not intuitive. How about 
checking in a pdf version to avoid rebuilding it every time?

**Comment by jstolarek** [comment]
But the paper is available online. I bet no one builds it from the repo.

**Comment by mlite** [comment]
Yes, it is online.    I found it's convenient having one around and 
actually built it.

I agree the latex code should be removed from this repo as the paper was 
published and none will contribute to it.  On the other hand, the paper 
is  an important documentation for understanding the design principle of 
the library.   The haddock documentation in the code is not sufficient.

We can keep the paper until we port some examples to haddock.  The 
current implementation has evolved from the one documented in the paper, 
this need to be noted in haddock to avoid any confusions.

**Comment by michalt** [comment]
So the paper is already linked at the top of the hackage documentation:
https://hackage.haskell.org/package/hoopl
So maybe we should just include the link in the README too (so that it's easily accessible when looking at the project on github) and then just remove the paper? I doubt many people would go about building it from source given that it's so easy to download. And all those additional markers in source code do make it slightly less readable and harder to change.

**Comment by jstolarek** [comment]
I second Michal's opinion. Really, the paper should not be in the repo. Many libraries are based on papers but they don't keep these papers inside the repo. Adding a link to README might be a good idea.

**Comment by mlite** [comment]
Please create a pull request to remove the latex code.

Let's keep the pdf version in the repo for now.

Thanks,
Ning

**Comment by mlite** [comment]
To clarify a bit. I will create a repo for external hoopl docs, then we move the pdf paper to the repo.

**Comment by michalt** [comment]
Sounds good! :-) I've sent the PR removing `paper/` (and the markers). Thanks!

**Comment by jstolarek** [comment]
Merged as 26a429c02ab6333b7194bddcc91b35a4d994f3ff

**Pull request closed without merging**
